[package]
name = "ebup-viewer-tauri"
version = "0.1.0"
edition = "2024"

[lib]
name = "ebup_viewer_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
epub = "2.1.5"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
tauri = { version = "2.10.2", features = [] }
tauri-plugin-log = "2.8.0"
toml = "1"
tracing = "0.1"

[build-dependencies]
tauri-build = { version = "2.5.5", features = [] }
