[package]
name = "ebup-viewer-tauri"
version = "0.1.0"
edition = "2024"

[lib]
name = "ebup_viewer_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
anyhow = "1"
ctrlc = "3.5.2"
epub = "2.1.5"
html2text = "0.16.4"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
once_cell = "1.19"
regex = "1.12"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2.10.2", features = [] }
tauri-plugin-log = "2.8.0"
toml = "1"
tracing = "0.1"
ts-rs = { version = "10.0.0", features = ["serde-compat"] }
unicode-normalization = "0.1.25"

[build-dependencies]
tauri-build = { version = "2.5.5", features = [] }
