[abbreviations.nocase]
"rev." = "revised"
"vol." = "volume"
"chap." = "chapter"
"pp." = "pages"
"etc." = "et cetera"
"i.e." = "that is"
"e.g." = "for example"
"vs." = "versus"
"ibid." = "in the same place"
"p." = "page"

[abbreviations.case]
# Example:
# "US." = "United States"
"M." = "M"
"B." = "B"
"Dr." = "Doctor"
"Inc." = "Incorporated"
"Mr." = "Mister"
"Ms." = "Miss"
"Mrs." = "Misses"
"Mass." = "Massachusetts"
"St." = "Saint"

# Month abbreviations.
"Jan." = "January"
"Feb." = "February"
"Mar." = "March"
"Apr." = "April"
"Jun." = "June"
"Jul." = "July"
"Aug." = "August"
"Sep." = "September"
"Oct." = "October"
"Nov." = "November"
"Dec." = "December"

# Day-of-week abbreviations.
"Mon." = "Monday"
"Tue." = "Tuesday"
"Wed." = "Wednesday"
"Thu." = "Thursday"
"Fri." = "Friday"
"Sat." = "Saturday"
"Sun." = "Sunday"

# US state abbreviations.
"AL" = "Alabama"
"AK" = "Alaska"
"AZ" = "Arizona"
"AR" = "Arkansas"
"CA" = "California"
"CO" = "Colorado"
"CT" = "Connecticut"
"DE" = "Delaware"
"FL" = "Florida"
"GA" = "Georgia"
"HI" = "Hawaii"
"ID" = "Idaho"
"IL" = "Illinois"
"IN" = "Indiana"
"IA" = "Iowa"
"KS" = "Kansas"
"KY" = "Kentucky"
"LA" = "Louisiana"
"ME" = "Maine"
"MD" = "Maryland"
"MA" = "Massachusetts"
"MI" = "Michigan"
"MN" = "Minnesota"
"MS" = "Mississippi"
"MO" = "Missouri"
"MT" = "Montana"
"NE" = "Nebraska"
"NV" = "Nevada"
"NH" = "New Hampshire"
"NJ" = "New Jersey"
"NM" = "New Mexico"
"NY" = "New York"
"NC" = "North Carolina"
"ND" = "North Dakota"
"OH" = "Ohio"
"OK" = "Oklahoma"
"OR" = "Oregon"
"PA" = "Pennsylvania"
"RI" = "Rhode Island"
"SC" = "South Carolina"
"SD" = "South Dakota"
"TN" = "Tennessee"
"TX" = "Texas"
"UT" = "Utah"
"VT" = "Vermont"
"VA" = "Virginia"
"WA" = "Washington"
"WV" = "West Virginia"
"WI" = "Wisconsin"
"WY" = "Wyoming"

# Alt US state abbreviations.
"Ala." = "Alabama"