[abbreviations.nocase]

[abbreviations.case]

# Text abbreviations.
"ed." = "edition"
"sect." = "section"
"rev." = "revised"
"vol." = "volume"
"chap." = "chapter"
"pp." = "pages"
"etc." = "et cetera"
"i.e." = "that is"
"e.g." = "for example"
"ibid." = "in the same place"
"p." = "page"
"vs." = "versus"

# Number suffixes.
"II" = "the second"
"III" = "the third"
"IV" = "the fourth"
"V" = "the fifth"
"VI" = "the sixth"

# Title suffixes.
"Jr." = "Junior"
"Sr." = "Senior"
"Dr." = "Doctor"
"Inc." = "Incorporated"
"Mr." = "Mister"
"Ms." = "Miss"
"Mrs." = "Misses"
"St." = "Saint"

# Month abbreviations.
"Jan." = "January"
"Feb." = "February"
"Mar." = "March"
"Apr." = "April"
"Jun." = "June"
"Jul." = "July"
"Aug." = "August"
"Sep." = "September"
"Oct." = "October"
"Nov." = "November"
"Dec." = "December"

# Day-of-week abbreviations.
"Mon." = "Monday"
"Tue." = "Tuesday"
"Wed." = "Wednesday"
"Thu." = "Thursday"
"Fri." = "Friday"
"Sat." = "Saturday"
"Sun." = "Sunday"

# US state abbreviations.
"AL" = "Alabama"
"AK" = "Alaska"
"AZ" = "Arizona"
"AR" = "Arkansas"
"CA" = "California"
"CO" = "Colorado"
"CT" = "Connecticut"
"DE" = "Delaware"
"FL" = "Florida"
"GA" = "Georgia"
"HI" = "Hawaii"
"ID" = "Idaho"
"IL" = "Illinois"
"IN" = "Indiana"
"IA" = "Iowa"
"KS" = "Kansas"
"KY" = "Kentucky"
"LA" = "Louisiana"
"ME" = "Maine"
"MD" = "Maryland"
"MA" = "Massachusetts"
"MI" = "Michigan"
"MN" = "Minnesota"
"MS" = "Mississippi"
"MO" = "Missouri"
"MT" = "Montana"
"NE" = "Nebraska"
"NV" = "Nevada"
"NH" = "New Hampshire"
"NJ" = "New Jersey"
"NM" = "New Mexico"
"NY" = "New York"
"NC" = "North Carolina"
"ND" = "North Dakota"
"OH" = "Ohio"
"OK" = "Oklahoma"
"OR" = "Oregon"
"PA" = "Pennsylvania"
"RI" = "Rhode Island"
"SC" = "South Carolina"
"SD" = "South Dakota"
"TN" = "Tennessee"
"TX" = "Texas"
"UT" = "Utah"
"VT" = "Vermont"
"VA" = "Virginia"
"WA" = "Washington"
"WV" = "West Virginia"
"WI" = "Wisconsin"
"WY" = "Wyoming"

# Alt US state abbreviations.
"Ala." = "Alabama"
"Calif." = "California"
"Mass." = "Massachusetts"
"Va." = "Virginia"
"N.J." = "New Jersey"
"Ind." = "Indiana"


# Letter middle names.
"A." = "A"
"B." = "B"
"C." = "C"
"D." = "D"
"E." = "E"
"F." = "F"
"G." = "G"
"H." = "H"
"I." = "I"
"J." = "J"
"K." = "K"
"L." = "L"
"M." = "M"
"N." = "N"
"O." = "O"
"P." = "P"
"Q." = "Q"
"R." = "R"
"S." = "S"
"T." = "T"
"U." = "U"
"V." = "V"
"W." = "W"
"X." = "X"
"Y." = "Y"
"Z." = "Z"

[[abbreviations.regex]]
pattern = '\bp\.\s*(\d+)\.?'
replace = 'page $1'
case_sensitive = true

[[abbreviations.regex]]
pattern = '\b(\d+)-(\d+)\b'
replace = '$1 to $2'
case_sensitive = true
