[abbreviations]
"Mr." = "Mister"
"Ms." = "Miss"
"Mrs." = "Misses"
"Mass." = "Massachusetts"
"St." = "Saint"
"M." = ""
"pp." = "pages"
"Dr." = "Doctor"
"Inc." = "Incorporated"
"etc." = "et cetera"
"i.e." = "that is"
"e.g." = "for example"
"vs." = "versus"
"ibid." = "in the same place"
"p." = "page"
"Jan." = "January"
"Feb." = "February"
"Mar." = "March"
"Apr." = "April"
"Jun." = "June"
"Jul." = "July"
"Aug." = "August"
"Sep." = "September"
"Oct." = "October"
"Nov." = "November"
"Dec." = "December"
"Mon." = "Monday"
"Tue." = "Tuesday"
"Wed." = "Wednesday"
"Thu." = "Thursday"
"Fri." = "Friday"
"Sat." = "Saturday"
"Sun." = "Sunday"
