theme = "day"
font_size = 16
line_spacing = 1.3
margin_horizontal = 0
margin_vertical = 0
font_family = "lexend"
font_weight = "bold"
justification = "justified"
word_spacing = 0
letter_spacing = 0
show_tts = true
show_settings = true
# TTS configuration
tts_model_path = "/usr/share/piper-voices/en/en_US/ryan/high/en_US-ryan-high.onnx"
tts_espeak_path = "/usr/share/espeak-ng-data"
tts_speed = 1.0
